@echo off
rem Builds a release and wraps it up as a zip somebody can be handed.
rem
rem Everything the game needs at runtime goes in and nothing else does: the
rem executable, the two SDL runtime DLLs, and the assets folder it finds
rem through SDL_GetBasePath. No installer, no dependencies, no build tools -
rem unzip it anywhere and run it.
rem
rem   tools\package.bat            ->  dist\claudaga.zip
rem   tools\package.bat 1.0        ->  dist\claudaga-1.0.zip

setlocal
set "ROOT=%~dp0.."
set "TAR=%SystemRoot%\System32\tar.exe"

if not exist "%TAR%" (
    echo [pack] ERROR: %TAR% not found - Windows 10 1803 or later is expected.
    exit /b 1
)

rem --- 1. a release build, from scratch -----------------------------------
rem Wiped first so nothing from an old debug build can ride along; the same
rem folder holds both configurations.
if exist "%ROOT%\build" rmdir /s /q "%ROOT%\build"

call "%ROOT%\build.bat" release
if errorlevel 1 (
    echo [pack] ERROR: the release build failed - nothing was packaged.
    exit /b 1
)

rem --- 2. stage exactly what ships ----------------------------------------
set "NAME=claudaga"
if not "%~1"=="" set "NAME=claudaga-%~1"

set "STAGE=%ROOT%\dist\%NAME%"
if exist "%STAGE%" rmdir /s /q "%STAGE%"
mkdir "%STAGE%" 2>nul

copy /y "%ROOT%\build\claudaga.exe"    "%STAGE%\" >nul
copy /y "%ROOT%\build\SDL2.dll"        "%STAGE%\" >nul
copy /y "%ROOT%\build\SDL2_mixer.dll"  "%STAGE%\" >nul
copy /y "%ROOT%\LICENSE"              "%STAGE%\LICENSE.txt" >nul

mkdir "%STAGE%\assets" 2>nul

rem The exclude list keeps out things that live in assets but are not the
rem game's: a sync client on the working share drops "Working Copy of ..."
rem beside edited files, and one of those went out in the first archive this
rem script built. xcopy matches each pattern against the whole path, and the
rem list is passed relative to the project root because /EXCLUDE will not take
rem a quoted path and the root may contain spaces.
pushd "%ROOT%"
xcopy /y /q /e /exclude:tools\pack_exclude.txt "%ROOT%\assets" "%STAGE%\assets\" >nul
popd

rem The .pdb is deliberately not here. It is worth keeping for a crash report
rem but it is four megabytes of no use to a player.

rem --- 3. a note for whoever opens it -------------------------------------
> "%STAGE%\README.txt" echo CLAUDAGA
>>"%STAGE%\README.txt" echo ========
>>"%STAGE%\README.txt" echo.
>>"%STAGE%\README.txt" echo A Galaga clone. Unzip anywhere and run claudaga.exe -
>>"%STAGE%\README.txt" echo there is nothing to install.
>>"%STAGE%\README.txt" echo.
>>"%STAGE%\README.txt" echo CONTROLS
>>"%STAGE%\README.txt" echo   Keyboard   arrows to fly, space to fire
>>"%STAGE%\README.txt" echo   Controller stick or d-pad to fly, A to fire
>>"%STAGE%\README.txt" echo   P          pause
>>"%STAGE%\README.txt" echo   F11        full screen ^(Alt+Enter also works^)
>>"%STAGE%\README.txt" echo   Escape     back to the menu
>>"%STAGE%\README.txt" echo.
>>"%STAGE%\README.txt" echo Options on the title screen sets the sound and music
>>"%STAGE%\README.txt" echo levels and full screen. Those and the high score are
>>"%STAGE%\README.txt" echo remembered in:
>>"%STAGE%\README.txt" echo.
>>"%STAGE%\README.txt" echo   %%APPDATA%%\Claudaga\Claudaga\
>>"%STAGE%\README.txt" echo.
>>"%STAGE%\README.txt" echo Deleting that folder resets everything.
>>"%STAGE%\README.txt" echo.
>>"%STAGE%\README.txt" echo The game is zlib licensed - see LICENSE.txt.
>>"%STAGE%\README.txt" echo Sound and music are other people's work, all of it
>>"%STAGE%\README.txt" echo public domain - see assets\audio\CREDITS.txt.
>>"%STAGE%\README.txt" echo Everything drawn on screen is generated by the game.

rem --- 4. nothing ships unverified ----------------------------------------
rem A copy that fails does not stop a batch file, and this script once zipped
rem a package with no executable in it and said OK. The same check the CI
rem workflow runs, run here for the same reason.
for %%F in (claudaga.exe SDL2.dll SDL2_mixer.dll LICENSE.txt README.txt assets\audio\CREDITS.txt) do (
    if not exist "%STAGE%\%%F" (
        echo [pack] ERROR: %%F missing from the staged package - not zipping it.
        exit /b 1
    )
)

rem --- 5. zip it ----------------------------------------------------------
rem tar picks the format from the extension with -a, so this really is a zip
rem and not a tarball wearing one's name. Run from dist so the archive holds
rem one folder rather than a path.
pushd "%ROOT%\dist"
if exist "%NAME%.zip" del /q "%NAME%.zip"
"%TAR%" -a -c -f "%NAME%.zip" "%NAME%"
if errorlevel 1 (
    popd
    echo [pack] ERROR: could not create the zip.
    exit /b 1
)
popd

for %%F in ("%ROOT%\dist\%NAME%.zip") do set "BYTES=%%~zF"
set /a KB=%BYTES% / 1024
echo [pack] OK -^> dist\%NAME%.zip ^(%KB% KB^)
exit /b 0
